# Generated by Django 2.0.9 on 2018-11-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='decription',
            new_name='description',
        ),
    ]
