# Generated by Django 2.0.9 on 2018-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20181116_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seller',
            field=models.CharField(choices=[('os', 'onsale'), ('cp', 'contract_pending'), ('sd', 'sold')], default='os', max_length=16),
        ),
    ]
