# Generated by Django 2.0.9 on 2018-11-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20181117_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(choices=[('On Sale', 'onsale'), ('Contract Pending', 'contract_pending'), ('Sold', 'sold')], default='On Sale', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Sale'),
        ),
    ]
