# Generated by Django 2.0.9 on 2018-11-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_auto_20181117_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_state', models.CharField(choices=[('On Sale', 'onsale'), ('Contract Pending', 'contract_pending'), ('Sold', 'sold')], default='On Sale', max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='seller',
        ),
        migrations.AddField(
            model_name='sell',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='realestate.Post'),
        ),
    ]
