# Generated by Django 2.0.9 on 2018-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_auto_20181120_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='seller',
            field=models.CharField(choices=[('On Sale', 'onsale'), ('Contract Pending', 'contract_pending'), ('Sold', 'sold')], default='On Sale', max_length=16),
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
